# testing - this is a basic workflow to help you get started
name: CI
# Controls when the workflow will run
on:
  push:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: running echo
        run: pwd; cat /etc/os* ; ls -lrt; df -h; free -h
  
